import { Router } from "express";
import * as books from "./book.controller.js";
import { auth } from "../../middlewares/authen.middleware.js";
import { errorHandler } from "../../middlewares/error-handling.middleware.js";
const router = Router();
router.post("/addBook", errorHandler(books.addBook));
router.patch("/updateBook/:id", errorHandler(books.updateBook));
router.patch("/updateBookAuthor/:id", errorHandler(books.updateBookAuthor));
router.delete("/deleteBook/:id", errorHandler(books.deleteBook));
router.get("/getAllBooksOfAuthor",auth(), errorHandler(books.getAllBooks));
router.get("/getSpecfic/:id", errorHandler(books.getABook));
router.get("/search",errorHandler(books.search));
export default router;
