import { Router } from "express";
import * as auhtors from "./author.controller.js";
import { auth } from "../../middlewares/authen.middleware.js";
import { errorHandler } from "../../middlewares/error-handling.middleware.js";
const router = Router();
router.post("/signUp", errorHandler(auhtors.signUp));
router.post("/login",errorHandler(auhtors.signIn));
router.get("/getAll", errorHandler(auhtors.getAllAuthors));
router.get("/getAnAuthor/:id",errorHandler( auhtors.getAnAuthor));
router.patch("/updateAuthor",auth(), errorHandler(auhtors.updateAuthor));
router.delete("/deleteAuthor", auth(), errorHandler(auhtors.deleteAuthor));
router.get("/search",errorHandler(auhtors.search));
router.get("/confirmation/:confirmationToken",errorHandler(auhtors.verifyEmail));
export default router;
